name: object-detection
channels: !!python/tuple
- menpo
- defaults
dependencies:
- cycler=0.10.0=py35_0
- freetype=2.5.5=2
- icu=54.1=0
- jbig=2.1=0
- jlaura::opencv3=3.0.0=py35_0
- jpeg=9b=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- matplotlib=2.0.2=np113py35_0
- menpo::tbb=4.3_20141023=0
- mkl=2017.0.1=0
- numpy=1.13.0=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2l=0
- pillow=4.1.1=py35_0
- pip=9.0.1=py35_1
- py=1.4.34=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- pytest=3.2.1=py35_0
- python=3.5.3=1
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=2
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - backports.weakref==1.0rc1
  - bleach==1.5.0
  - html5lib==0.9999999
  - markdown==2.2.0
  - protobuf==3.3.0
  - tensorflow==1.2.0
  - werkzeug==0.12.2
prefix: /Users/datitran/anaconda/envs/object-detection

